const fs = require('fs');

let fileStr = fs.readFileSync('src/pages/Admin/index.jsx', 'utf8');

const t2 = `        } else if (user) {
            loadDashboardData();
        }
        return () => clearInterval(interval);
    }, [demoMode]);

    // "Last updated" ticker
    useEffect(() => {
        if (!lastMqttAt) {
            setSecondsSinceUpdate(null);
            return;
        }
        const t = setInterval(() => {
            setSecondsSinceUpdate(Math.max(0, Math.floor((Date.now() - lastMqttAt) / 1000)));
        }, 1000);
        return () => clearInterval(t);
    }, [lastMqttAt]);

    // -------------------------------------------------------------
    // HANDLERS
    // -------------------------------------------------------------
    const handleOverride = async (level) => {
        if(!isHeadAdmin) {
            alert('Only Head Admins can override the system alarm.');
            return;
        }

        let reason = "";
        if (level !== 'NORMAL') {
            reason = prompt(\`Reason for Manual Override to \${level}:\`);
            if (reason === null) return; // Cancelled
        }

        if(!window.confirm(\`Are you sure you want to broadcast a \${level} alert?\`)) return;

        try {
            const actor = \`\${displayName}\${user?.id ? \` (\${user.id})\` : ''}\`;
            const safeReason = \`\${reason || 'Admin Manual Action'} [override by \${actor}]\`;
            await overrideAlert(level, safeReason);
            alert(\`Alert level forcefully overridden to \${level}\`);
            loadDashboardData();
            if(isHeadAdmin) loadAdminUsersData(); // Reload logs
        } catch(e) {
            alert('Error overriding alert.');
        }
    };

    const handleDownloadReport = async (format) => {
        if (format !== 'xlsx') return;
        try {
            const telemetryData = await fetchSensorData(24 * 7); // Export 7 days
            const safeData = Array.isArray(telemetryData) ? telemetryData : [];
            const start = reportStart ? new Date(\`\${reportStart}T00:00:00\`) : null;
            const end = reportEnd ? new Date(\`\${reportEnd}T23:59:59\`) : null;
            const filtered = safeData.filter(d => {
                const ts = d?.timestamp ? new Date(d.timestamp) : null;
                if (!ts || Number.isNaN(ts.getTime())) return false;
                if (start && ts < start) return false;
                if (end && ts > end) return false;
                return true;
            });

            const wb = new ExcelJS.Workbook();
            const ws = wb.addWorksheet('SurgeAlert Report');

            ws.addRow(['SurgeAlert Official Data Report']);
            ws.getRow(1).font = { size: 16, bold: true, color: { argb: 'FF004B87' } };
            ws.addRow([]);

            ws.addRow(['Metric', 'Value']).font = { bold: true };
            ws.addRow(['Generated At', new Date().toLocaleString()]);
            ws.addRow(['Generated By', displayName]);
            ws.addRow(['Date Range', \`\${reportStart || '—'} to \${reportEnd || '—'}\`]);
            ws.addRow(['Rows Exported', String(filtered.length)]);
            ws.addRow([]);

            ws.addRow(['Data Export']).font = { size: 14, bold: true };
            
            const columns = [{ header: 'Timestamp', key: 'ts', width: 25 }];
            if (reportTelemetry) {
                columns.push({ header: 'Water Level (m)', key: 'wl', width: 18 });
                columns.push({ header: 'Flow Rate (m/s)', key: 'fr', width: 18 });
            }
            if (reportAI) {
                columns.push({ header: 'ML Predicted Level (m)', key: 'ai', width: 22 });
            }
            ws.columns = columns;

            const headerRow = ws.getRow(ws.rowCount);
            headerRow.eachCell((cell) => {
                cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
                cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E293B' } };
            });

            filtered.forEach(d => {
                const rowObj = { ts: new Date(d.timestamp).toLocaleString() };
                if (reportTelemetry) {
                    rowObj.wl = d.waterLevelM;
                    rowObj.fr = d.sensorFlowRateMps;
                }
                if (reportAI) {
                    rowObj.ai = d.predictedLevel;
                }
                ws.addRow(rowObj);
            });

            const buffer = await wb.xlsx.writeBuffer();
            const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
            saveAs(blob, \`SurgeAlert_Report_\${new Date().toISOString().slice(0,10)}.xlsx\`);

            if(isHeadAdmin) loadAdminUsersData();
        } catch (e) {
            console.error(e);
            alert('Error generating report.');
        }
    };

    const handleDeleteResident = async (id, label) => {
        if (!window.confirm('Remove subscriber ' + (label || id) + '?')) return;
        try {
            await deleteResidentAPI(id);
            loadResidents();
            loadDashboardData();
        } catch (e) { alert('Delete failed'); }
    };

    const handleAddManualResident = async (e) => {
        e.preventDefault();
        try {
            await registerResident({ 
                fullName: newResidentState.name, 
                phoneNumber: newResidentState.phone 
            });
            setIsAddingResident(false);
            setNewResidentState({ name: '', phone: '' });
            loadResidents();
            loadDashboardData();
            alert('Resident manually added successfully.');
        } catch(e) {
            alert('Error adding resident: ' + e.message);
        }
    };

    const handleSaveTemplate = async (type, template) => {
        try {
            await saveTemplateAPI(type, template);
            setTemplates(prev => prev.map(t => (String(t.alertType).toUpperCase() === String(type).toUpperCase() ? { ...t, template } : t)));
            alert(\`\${type} Template updated!\`);
        } catch (e) { alert("Failed update."); }
    };

    const beginEditTemplate = (type, currentText) => {
        const key = String(type || '').toUpperCase();
        setEditingTemplateType(key);
        setTemplateDrafts(prev => ({ ...prev, [key]: backendToUI(currentText ?? prev[key] ?? '') }));
    };

    const cancelEditTemplate = () => {
        setEditingTemplateType(null);
    };

    const saveEditedTemplate = async (type) => {`;

const userPartIndex = fileStr.indexOf('        } else if (user) {');
const savePartIndex = fileStr.indexOf('        // Ensure no legacy placeholders are left');

if (userPartIndex === -1 || savePartIndex === -1) {
    console.log('CANT FIND', userPartIndex, savePartIndex);
    process.exit(1);
}

// "    const saveEditedTemplate = async (type) => {"
// The tool deleted everything up to `// Ensure no legacy...`
// My t2 block ends with `const saveEditedTemplate = async (type) => {`.
const start = userPartIndex;
const end = savePartIndex - "        // Ensure no legacy placeholders are left".length + "        // Ensure no legacy placeholders are left".length;

const before = fileStr.substring(0, start);
const after = fileStr.substring(savePartIndex - "        let normalized = uiToBackend(String(next));\n        \n".length);

fs.writeFileSync('src/pages/Admin/index.jsx', before + t2 + "\n        const key = String(type || '').toUpperCase();\n        const next = templateDrafts[key] ?? '';\n        let normalized = uiToBackend(String(next));\n        \n" + fileStr.substring(savePartIndex));
console.log('PERFECTLY FIXED.');
